name: Build and Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  buildAndTest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: '5.9'
    - uses: actions/cache@v2
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: CocoaPod Install
      run: pod install
    - name: Build
      run: xcodebuild -workspace Versus.xcworkspace -scheme Versus-iOS -configuration Release -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12'
    - name: Test
      run: xcodebuild -workspace Versus.xcworkspace -scheme Versus-iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12' test
